# Generated by Django 4.0.1 on 2022-01-18 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Longitud')),
                ('date_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Fecha y Hora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
