# Generated by Django 4.0.1 on 2022-01-21 17:28

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_location_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_time',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.utcnow, help_text='Probando si sale el help text', verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=7, help_text='Maximo 7 decimales. Ej: -27.0697049', max_digits=9, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=7, help_text='Maximo 7 decimales. Ej: -70.8177738', max_digits=9, verbose_name='Longitud'),
        ),
    ]
