version: '3.8'

services:
  web:
    build: ./
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=houm
      - POSTGRES_PASSWORD=houm
      - POSTGRES_DB=houm
  nginx:
    build: ./nginx
    ports:
      - 1337:8080
    depends_on:
      - web

volumes:
  postgres_data: